NAME    = libft.a

MANDATORY_SRCS = ft_atoi.c ft_isalpha.c ft_isdigit.c ft_isalnum.c  ft_isascii.c ft_isprint.c ft_strlen.c ft_memset.c\
					ft_bzero.c ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c\
					ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c ft_calloc.c ft_strdup.c\
					ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c \
					ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c utils.c ft_printf.c get_next_line.c \
					get_next_line_utils.c ft_strcmp.c get_next_line_new.c
		
BONUS_SRCS	=	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c \
					ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c 	


# M_OBJS = $(MANDATORY_SRCS:.c=.o)
# B_OBJS = $(BONUS_SRCS:.c=.o)

# LIBCR   = ar -rc
# CC      = gcc
# RM      = rm -f
# CFLAGS  = -Wall -Wextra -Werror -I../includes

# all: $(NAME)

# .c.o: 
# 	@$(CC) $(CFLAGS) -c $< -o $(<:.c=.o) 

# $(NAME): $(M_OBJS)
# 	@$(LIBCR) $(NAME) $(M_OBJS)
	
# clean:
# 	@$(RM) $(M_OBJS) $(B_OBJS)

# fclean: clean
# 		@$(RM) $(NAME)

# re: fclean  all

# bonus: $(M_OBJS) $(B_OBJS)
# 	$(LIBCR) $(NAME) $(M_OBJS) $(B_OBJS)


cp ft_atoi.c ft_atoi.cpoopy
cp ft_isalpha.c ft_isalpha.cpoopy
cp ft_isdigit.c ft_isdigit.cpoopy
cp ft_isalnum.c ft_isalnum.cpoopy
cp ft_isascii.c ft_isascii.cpoopy
cp ft_isprint.c ft_isprint.cpoopy
cp ft_strlen.c ft_strlen.cpoopy
cp ft_memset.c ft_memset.cpoopy
cp ft_bzero.c ft_bzero.cpoopy
cp ft_memcpy.c ft_memcpy.cpoopy
cp ft_memmove.c ft_memmove.cpoopy
cp ft_strlcpy.c ft_strlcpy.cpoopy
cp ft_strlcat.c ft_strlcat.cpoopy
cp ft_toupper.c ft_toupper.cpoopy
cp ft_tolower.c ft_tolower.cpoopy
cp ft_strchr.c ft_strchr.cpoopy
cp ft_strrchr.c ft_strrchr.cpoopy
cp ft_strncmp.c ft_strncmp.cpoopy
cp ft_memchr.c ft_memchr.cpoopy
cp ft_memcmp.c ft_memcmp.cpoopy
cp ft_strnstr.c ft_strnstr.cpoopy
cp ft_calloc.c ft_calloc.cpoopy
cp ft_strdup.c ft_strdup.cpoopy
cp ft_substr.c ft_substr.cpoopy
cp ft_strjoin.c ft_strjoin.cpoopy
cp ft_strtrim.c ft_strtrim.cpoopy
cp ft_split.c ft_split.cpoopy
cp ft_itoa.c ft_itoa.cpoopy
cp ft_strmapi.c ft_strmapi.cpoopy
cp ft_striteri.c ft_striteri.cpoopy
cp ft_putchar_fd.c ft_putchar_fd.cpoopy
cp 	
cp ft_putstr_fd.c ft_putstr_fd.cpoopy
cp ft_putendl_fd.c ft_putendl_fd.cpoopy
cp ft_putnbr_fd.c ft_putnbr_fd.cpoopy
cp utils.c utils.cpoopy
cp ft_printf.c ft_printf.cpoopy
cp get_next_line.c get_next_line.cpoopy
cp 	
cp get_next_line_utils.c get_next_line_utils.cpoopy
cp ft_strcmp.c ft_strcmp.cpoopy
cp get_next_line_new.c get_next_line_new.cpoopy
cp ft_lstnew.c ft_lstnew.cpoopy
cp ft_lstadd_front.c ft_lstadd_front.cpoopy
cp ft_lstsize.c ft_lstsize.cpoopy
cp ft_lstlast.c ft_lstlast.cpoopy
cp ft_lstadd_back.c ft_lstadd_back.cpoopy
cp 	
cp ft_lstdelone.c ft_lstdelone.cpoopy
cp ft_lstclear.c ft_lstclear.cpoopy
cp ft_lstiter.c ft_lstiter.cpoopy
cp ft_lstmap.c ft_lstmap.cpoopy